// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	trace "go.opentelemetry.io/otel/sdk/trace"
)

// TracerProvider is an autogenerated mock type for the TracerProvider type
type TracerProvider struct {
	mock.Mock
}

// InitTracerProvider provides a mock function with given fields: ctx
func (_m *TracerProvider) InitTracerProvider(ctx context.Context) (*trace.TracerProvider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitTracerProvider")
	}

	var r0 *trace.TracerProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*trace.TracerProvider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *trace.TracerProvider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trace.TracerProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTracerProvider creates a new instance of TracerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTracerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TracerProvider {
	mock := &TracerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
