// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	frame "github.com/datastax/go-cassandra-native-protocol/frame"

	message "github.com/datastax/go-cassandra-native-protocol/message"

	mock "github.com/stretchr/testify/mock"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: hdr, msg
func (_m *Sender) Send(hdr *frame.Header, msg message.Message) {
	_m.Called(hdr, msg)
}

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
